### ISSUE TITLE
a error when LOCAL_UID and LOCAL_GID are not specified

### ISSUE THREAD

**Issue by tkmnet** [crest-cassia/oacis_docker#69]
LOCAL_UIDとLOCAL_GIDを指定しないで起動した際（マウントをしないで使いたい時）に，
public/Result_development がrootで作成されたままになっていて，正常に動作させることができないです．

**Comment by yohm** [comment]
マウント先のディレクトリを事前に作っておかないと（LOCAL_UID,GID関係なしに）rootになってしまうみたいです。
試しに事前にマウント先をmkdirで作って見てください。

**Comment by tkmnet** [comment]
現状はpublic/Result_developmentをchown oacis:oacisして使うようにしています．

**Comment by yohm** [comment]
こちら #70 で修正されました。closeします。
