### ISSUE TITLE
コンテナからリモートに接続する方法

### ISSUE THREAD

**Issue by SoyaMiyoshi** [crest-cassia/oacis_docker#78]
ドキュメント通り  
```
docker run --name my_oacis -p 127.0.0.1:3000:3000 -dt oacis/oacis
```  
で作成したコンテナは、デフォルトで接続先(ジョブsubmit先)はconfig上でlocalhostになっていると思います。

リモートのホストにコンテナから接続したい場合、
```
docker exec -it コンテナid /bin/bash
```  
を実行しコンテナのシェルをつつき、sshの設定をし直さなければならないのではないでしょうか。  
つまりコンテナの公開鍵をリモートに登録して、コンテナとリモートがssh通信できるようにしなければならないのでしょうか。  
(少なくても、私の環境ではそうでした。私はDockerに詳しくないのでグッドプラクティスかはわかりませんが、現在私はそうして使っています。）  

もしそれを想定している場合、ドキュメントにそのことを加筆した方がわかりやすいかなと思います。  
（もし可能であれば、私が加筆したいです。）  

ご検討お願いいいたします。

三好壮哉

**Comment by SoyaMiyoshi** [comment]
@yohm

**Comment by yohm** [comment]
@SoyaMiyoshi フィードバックありがとう。もしドキュメントを加筆してもらえるなら大変うれしいです！markdownで書かれているので、提案をPull Requestとして送ってみてもらえませんか？

**Comment by yohm** [comment]
Fixed by #79
